packages:
  - 'apps/*'

allowBuilds:
  '@firebase/util': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - protobufjs
